local:
  - hostname: jellyfin
    ip: 192.168.0.253

  - hostname: transmission
    ip: 192.168.0.36

tailscale:
  - hostname: jellyfin
    ip: 100.93.218.86

  - hostname: transmission
    ip: 100.93.99.60 
